### ISSUE TITLE
Initial Setup Help

### ISSUE THREAD

**Issue by bsullins** [assafgelber/jekyll-rss#18]
Sorry if this has been covered, couldn't find it in the previous issues or readme. I'm having trouble with the initial setup. Here is what I have in my _config.yml

```
plugins_dir: ./_plugins

plugins:
  - jekyll-rss

jekyll-rss:
  name: "Breaking Español"
  url: "http://breakingespanol.com"
  description: "One family's honest journey learning spanish"
  author: "Jennie Sullins"
  copyright: "Breaking Español"
  rss_path: "/"
  rss_name: "/feed.xml"
  rss_post_limit: 50
```

Then when visiting /feed.xml locally it gives a Not Found error. Is there something I'm missing here?

Thanks in advance,
Ben
